-- =====================================================================
-- 푸른홀딩스 공시자료 AI 도우미 — Supabase 테이블 설정
-- Supabase 대시보드 → 왼쪽 메뉴 "SQL Editor" → 아래 전체 복사 후 Run
-- =====================================================================

-- 1) 공시 지식 저장소 (AI가 '사실 근거'로 참고하는 자료) --------------
--    여기에 행을 추가할수록 챗봇이 더 정확해집니다. (챗봇이 '학습'하는 공간)
create table if not exists public.disclosures (
  id           bigint generated by default as identity primary key,
  title        text not null,               -- 자료 제목
  category     text,                         -- 분류 (예: 재무, 지배구조, 사업)
  content      text not null,                -- 본문(사실 내용)
  source_url   text,                         -- 출처 링크(선택)
  disclosed_at date,                          -- 공시/기준일(선택)
  created_at   timestamptz not null default now()
);

-- 2) 질문 추적 로그 (사람들이 무엇을 궁금해하는지 기록) ---------------
create table if not exists public.chat_logs (
  id          bigint generated by default as identity primary key,
  question    text not null,
  answer      text,
  created_at  timestamptz not null default now()
);

-- 3) 접근 정책(RLS) ---------------------------------------------------
alter table public.disclosures enable row level security;
alter table public.chat_logs  enable row level security;

-- 공시 지식: 누구나 읽기 가능(챗봇이 조회). 쓰기는 대시보드/서비스키로만.
drop policy if exists "disclosures_read" on public.disclosures;
create policy "disclosures_read" on public.disclosures
  for select using (true);

-- 질문 로그: 누구나 '추가(insert)'만 가능. 읽기는 막아둠(대시보드에서만 열람) → 질문이 외부에 노출되지 않음.
drop policy if exists "chat_logs_insert" on public.chat_logs;
create policy "chat_logs_insert" on public.chat_logs
  for insert with check (true);

-- 4) 초기 지식 시드(이미 공개된 사실 위주). 필요에 맞게 수정/추가하세요. -----
insert into public.disclosures (title, category, content, source_url, disclosed_at) values
('푸른홀딩스 개요', '그룹',
 '푸른홀딩스(PFG)는 푸른저축은행·푸른파트너스자산운용·푸른인베스트먼트를 계열로 두는 지주회사입니다. 저축은행(예금·대출), 자산운용(부동산 대체투자·PE·NPL), 벤처투자(신기술사업금융)로 사업을 구성합니다.',
 null, null),
('푸른저축은행', '계열사',
 '국내 저축은행 중 유일한 코스닥 상장사로, 예·적금·대출·전자금융 서비스를 제공합니다. 총자산은 약 1조 4천억 원 규모입니다. 상세 재무는 금융감독원 전자공시(DART)에서 확인할 수 있습니다.',
 'https://dart.fss.or.kr', null),
('푸른파트너스자산운용', '계열사',
 '2015년 설립된 전문사모운용사로, 국내 업계 최초로 부동산 사모대출펀드(PDF)를 선보였습니다. 부동산 대체투자·PE·NPL 전략을 운용하며 운용자산(AUM)은 약 4,500억 원 규모입니다.',
 null, null),
('푸른인베스트먼트', '계열사',
 '2021년 푸른파트너스자산운용의 PE부문을 물적분할해 출범한 신기술사업금융회사(VC)로, 로봇·콘텐츠·2차전지 등 미래 산업에 투자합니다. 운용자산은 약 2,400억 원 규모입니다.',
 null, null),
('지주회사 체제 전환 추진', '지배구조',
 '푸른그룹은 금융 계열사를 아우르는 지주회사 체제로의 전환을 추진하고 있습니다. 관련 절차에 따라 진행되며, 세부 내용은 상장사 공시를 통해 확인할 수 있습니다.',
 'https://dart.fss.or.kr', '2026-07-28');
